name: flutter_app
description: Flutter应用开发学习

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# 语义化版本规范（主版本号.次版本号.修订号）：https://semver.org/lang/zh-CN/
version: 1.0.0+1
author: 李玉江 <1032694760@qq.com>
homepage: https://github.com/gzu-liyujiang

environment:
  # 2.2.2之前的版本会报“suppress: sdk_version_ui_as_code”
  sdk: ">=2.2.2 <3.0.0"

# Flutter和Dart生态系统的共享软件包 https://pub.dev
# 关于版本号中的"^"说明,参见 https://codeday.me/bug/20190727/1549058.html
dependencies:
  # https://github.com/flutter/flutter
  flutter:
    sdk: flutter
  # 参阅《Flutter-国际化适配终结者》 https://www.jianshu.com/p/b9f830efe1f8
  flutter_localizations:
    sdk: flutter
  # SharedPreferences或NSUserDefaults https://github.com/flutter/plugins
  shared_preferences: ^0.5.3+4
  # 获取APP版本信息 https://github.com/flutter/plugins/tree/master/packages/package_info
  package_info: ^0.4.0+6
  # 启动URL https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^5.1.2
  # 调试日志工具类库 https://github.com/leisim/logger
  logger: ^0.7.0+2
  # 吐司 https://github.com/PonnamKarthik/FlutterToast
  # If you don't want to use androidx then use version 2.2.11
  fluttertoast: ^3.1.0
  # HTTP客户端 https://github.com/flutterchina/dio
  dio: ^2.1.13
  # 主题 https://github.com/Norbert515/dynamic_theme
  dynamic_theme: ^1.0.1
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^1.5.1
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^1.1.1
  # 用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.2.6+1
  # 荧光效果 https://github.com/hnvn/flutter_shimmer
  shimmer: ^1.0.0
  # 分享 https://github.com/flutter/plugins/tree/master/packages/share
  share: 0.6.2+1
  # Markdown文档 https://github.com/flutter/flutter_markdown
  flutter_markdown: ^0.2.0
  # 轮播图 https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # 网页加载 https://github.com/pichillilorenzo/flutter_inappbrowser
  flutter_inappbrowser: ^1.2.1
  # 下拉刷新上拉加载 https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^1.5.4
  # 向导页 https://github.com/duytq94/flutter-intro-slider
  intro_slider: ^2.2.7
  # 图片选择 https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: ^0.6.1+3
  # 图片预览 https://github.com/renancaraujo/photo_view
  photo_view: ^0.4.2
  # 图片裁剪 https://github.com/hnvn/flutter_image_cropper
  image_cropper: ^1.0.2
  # 文件下载 https://github.com/fluttercommunity/flutter_downloader
  #flutter_downloader: ^1.2.1
  # 键盘操作 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.2
  # 手势识别 https://github.com/aleksanderwozniak/simple_gesture_detector
  simple_gesture_detector: ^0.1.3
  # 依赖注入及状态管理 https://github.com/rrousselGit/provider
  provider: ^3.0.0+1
  # 日期时间滚轮选择 https://github.com/Realank/flutter_datetime_picker
  flutter_datetime_picker: ^1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - res/
    - res/values/
    - res/images/
    - res/images/home/

