name: CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: windows-latest
    #runs-on: macOS-latest
    steps: #See https://github.com/subosito/flutter-action
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.2' # you can use 1.7
          channel: 'stable' # optional, default to: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
